### ISSUE TITLE
Bug dist example 

### ISSUE THREAD

**Issue by sballieu** [linkedconnections/client.js#10]
When I execute the example in the dist folder I get an "write after end" error:

![error1](https://cloud.githubusercontent.com/assets/9060936/14409374/83687042-ff11-11e5-8a8c-fd3101bdfc43.png)

The error is caused because the stream is ended here: https://github.com/linkedconnections/client.js/blob/master/dist/example/index.js#L22

**Comment by pietercolpaert** [comment]
Indeed! Seems like that should have been a `source.close()` as documented in the README.md. Feel free to pull request the fix :)
