### ISSUE TITLE
Executing this query produces not results

### ISSUE THREAD

**Issue by rubensworks** [linkedconnections/client.js#6]
Execution simply halts, no output or errors are given.

``` json
{"departureTime": "2015-10-04T10:59:45.411Z","departureStop": "8814134","departureName": "Uccle-Calevoet","arrivalStop": "8883022","arrivalName": "Hennuyeres","duration": "7755000"}
```

**Comment by pietercolpaert** [comment]
Hm. Works for me... Let's debug earlier in the morning ;)

**Comment by pietercolpaert** [comment]
This should be fixed now

**Comment by pietercolpaert** [comment]
Ok, it doesn't work for me any longer either... Will debug!

**Comment by pietercolpaert** [comment]
I don't understand: looks like a problem with the gzipped response being cached, and the client on the command line not able to process this... Very strange...
